version: '3'
services:
   nodeapp:
      build:
         context: ./app
      container_name: nodeapp
      entrypoint: dockerize -wait tcp://db:3306 -timeout 30s node index.js
      restart: always
      networks:
         - node-network
      environment:
         - NODE_PORT=3000
      tty: true
      depends_on:
         - db
   db:
      image: mysql:5.7
      command: --innodb-use-native-aio=0
      container_name: db
      restart: always
      tty: true
      volumes:
         - ./config:/docker-entrypoint-initdb.d
         - ./database:/var/lib/mysql
      environment:
         - MYSQL_DATABASE=nodedb
         - MYSQL_ROOT_PASSWORD=iniciar
      networks:
         - node-network
   nginx:
      image: nginx:alpine
      container_name: nginx
      restart: always
      tty: true
      networks:
         - node-network
      ports:
         - '8080:80'
      volumes:
         - ./nginx:/etc/nginx/conf.d
      depends_on:
         - nodeapp
networks:
   node-network:
      driver: bridge
